@extends('layouts.app')

@section('title', 'Jadwal Kerja')

@section('sidebar')
    @include('components.operator-sidebar')
@endsection

@section('content')
<div class="container-fluid mt-4">

    {{-- Ultra Modern Header --}}
    <div class="position-relative overflow-hidden rounded-4 shadow-lg mb-4" style="background: linear-gradient(135deg, #10B981 0%, #059669 100%);">
        <div class="position-absolute top-0 end-0 opacity-25">
            <i class="fas fa-calendar-alt" style="font-size: 8rem; color: white; transform: rotate(15deg); margin: -2rem;"></i>
        </div>
        <div class="p-5 position-relative">
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <div class="d-flex align-items-center mb-2">
                        <h1 class="fw-bold mb-0 text-white">Jadwal Kerja</h1>
                    </div>
                    <p class="text-white-50 mb-0 fs-6">
                        📅 Kelola dan pantau jadwal kerja harian Anda
                    </p>
                </div>
            </div>
        </div>
    </div>

    {{-- Quick Stats --}}
    <div class="row g-4 mb-4" id="stats-container">
        <!-- Stats will be generated by JavaScript -->
    </div>

    {{-- Calendar View --}}
    <div class="row g-4">
        <div class="col-lg-8">
            <div class="card border-0 shadow-sm rounded-4">
                <div class="card-header bg-transparent border-0 p-4">
                    <div class="d-flex justify-content-between align-items-center">
                        <h5 class="fw-bold mb-0">📅 Kalender Jadwal</h5>
                    </div>
                </div>
                <div class="card-body p-4">
                    <div class="d-flex justify-content-between align-items-center mb-4">
                        <button class="btn btn-light rounded-circle" style="width: 40px; height: 40px;" onclick="changeMonth(-1)">
                            <i class="fas fa-chevron-left"></i>
                        </button>
                        <h4 class="fw-bold mb-0" id="calendar-title">Januari 2026</h4>
                        <button class="btn btn-light rounded-circle" style="width: 40px; height: 40px;" onclick="changeMonth(1)">
                            <i class="fas fa-chevron-right"></i>
                        </button>
                    </div>
                    
                    {{-- Calendar Grid --}}
                    <div class="table-responsive">
                        <table class="table table-borderless">
                            <thead>
                                <tr>
                                    <th class="text-center fw-semibold text-muted">Min</th>
                                    <th class="text-center fw-semibold text-muted">Sen</th>
                                    <th class="text-center fw-semibold text-muted">Sel</th>
                                    <th class="text-center fw-semibold text-muted">Rab</th>
                                    <th class="text-center fw-semibold text-muted">Kam</th>
                                    <th class="text-center fw-semibold text-muted">Jum</th>
                                    <th class="text-center fw-semibold text-muted">Sab</th>
                                </tr>
                            </thead>
                            <tbody id="calendar-body">
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        {{-- Schedule List --}}
        <div class="col-lg-4">
            <div class="card border-0 shadow-sm rounded-4">
                <div class="card-header bg-transparent border-0 p-4" id="schedule-header">
                    <h5 class="fw-bold mb-0">🕐 Jadwal Hari Ini</h5>
                    <small class="text-muted" id="current-date">Loading...</small>
                </div>
                <div class="card-body p-4" id="schedule-content">
                    <!-- Schedule content will be generated by JavaScript -->
                </div>
            </div>
        </div>
    </div>

</div>

{{-- Modal Tambah Jadwal --}}
<div class="modal fade" id="addScheduleModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content border-0 shadow-lg rounded-4">
            <div class="modal-header border-0 pb-0">
                <div class="text-center w-100">
                    <h3 class="fw-bold text-dark mb-2" style="background: linear-gradient(135deg, #10B981 0%, #059669 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;"> Tambah Jadwal Baru</h3>
                    <p class="text-muted mb-0 fs-6">Atur jadwal kerja dan shift dengan mudah</p>
                </div>
                <button type="button" class="btn-close position-absolute" data-bs-dismiss="modal" style="top: 15px; right: 15px;"></button>
            </div>
            <form id="scheduleForm">
                <div class="modal-body pt-3">
                    <div class="row g-4">
                        <div class="col-md-6">
                            <div class="form-floating">
                                <select class="form-select border-0 shadow-sm" id="scheduleType" style="background: linear-gradient(145deg, #f8f9fa 0%, #e9ecef 100%); border-radius: 15px; height: 60px;">
                                    <option value="shift">Shift Kerja</option>
                                    <option value="meeting">Meeting</option>
                                    <option value="maintenance">Maintenance</option>
                                    <option value="training">Training</option>
                                </select>
                                <label for="scheduleType" class="text-muted"><i class="fas fa-list me-2" style="background: linear-gradient(135deg, #10B981 0%, #059669 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;"></i>Jenis Jadwal</label>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-floating">
                                <input type="date" class="form-control border-0 shadow-sm" id="scheduleDate" style="background: linear-gradient(145deg, #f8f9fa 0%, #e9ecef 100%); border-radius: 15px; height: 60px;">
                                <label for="scheduleDate" class="text-muted"><i class="fas fa-calendar me-2" style="background: linear-gradient(135deg, #10B981 0%, #059669 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;"></i>Tanggal</label>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row g-4 mt-2">
                        <div class="col-md-6">
                            <div class="form-floating">
                                <input type="time" class="form-control border-0 shadow-sm" id="startTime" style="background: linear-gradient(145deg, #f8f9fa 0%, #e9ecef 100%); border-radius: 15px; height: 60px;">
                                <label for="startTime" class="text-muted"><i class="fas fa-clock me-2" style="background: linear-gradient(135deg, #10B981 0%, #059669 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;"></i>Waktu Mulai</label>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-floating">
                                <input type="time" class="form-control border-0 shadow-sm" id="endTime" style="background: linear-gradient(145deg, #f8f9fa 0%, #e9ecef 100%); border-radius: 15px; height: 60px;">
                                <label for="endTime" class="text-muted"><i class="fas fa-clock me-2" style="background: linear-gradient(135deg, #10B981 0%, #059669 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;"></i>Waktu Selesai</label>
                            </div>
                        </div>
                    </div>

                    <div class="mt-4">
                        <div class="form-floating">
                            <textarea class="form-control border-0 shadow-sm" id="scheduleDescription" placeholder="Deskripsi jadwal..." style="background: linear-gradient(145deg, #f8f9fa 0%, #e9ecef 100%); border-radius: 15px; height: 120px; resize: none;"></textarea>
                            <label for="scheduleDescription" class="text-muted"><i class="fas fa-align-left me-2" style="background: linear-gradient(135deg, #10B981 0%, #059669 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;"></i>Deskripsi</label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer border-0 pt-2">
                    <button type="button" class="btn btn-light rounded-pill px-4 py-2 me-2" data-bs-dismiss="modal" style="background: linear-gradient(145deg, #f8f9fa 0%, #e9ecef 100%); border: none; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
                        <i class="fas fa-times me-2"></i>Batal
                    </button>
                    <button type="submit" class="btn btn-primary rounded-pill px-4 py-2 shadow" style="background: linear-gradient(135deg, #10B981 0%, #059669 100%); border: none; box-shadow: 0 4px 15px rgba(59, 130, 246, 0.4);">
                        <i class="fas fa-save me-2"></i>Simpan Jadwal
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
        /* =========================
        CONSTANTS
        ========================= */
        const monthNames = [
            "Januari", "Februari", "Maret", "April", "Mei", "Juni",
            "Juli", "Agustus", "September", "Oktober", "November", "Desember"
        ];

        const dayNames = [
            "Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu"
        ];

        /* =========================
        STATE
        ========================= */
        let currentMonth = new Date().getMonth();
        let currentYear = new Date().getFullYear();
        let selectedDate = new Date();

        // Injected schedules from Controller
        let schedules = @json($schedules);

        /* =========================
        UTIL
        ========================= */
        function formatDate(date) {
            const y = date.getFullYear();
            const m = String(date.getMonth() + 1).padStart(2, "0");
            const d = String(date.getDate()).padStart(2, "0");
            return `${y}-${m}-${d}`;
        }

        /* =========================
        MONTH NAVIGATION
        ========================= */
        function changeMonth(direction) {
            currentMonth += direction;
            
            if (currentMonth > 11) {
                currentMonth = 0;
                currentYear++;
            } else if (currentMonth < 0) {
                currentMonth = 11;
                currentYear--;
            }
            
            renderCalendar();
        }

        /* =========================
        CALENDAR RENDER
        ========================= */
        function renderCalendar() {
            const tbody = document.getElementById("calendar-body");
            tbody.innerHTML = "";

            document.getElementById("calendar-title").textContent =
                `${monthNames[currentMonth]} ${currentYear}`;

            const firstDay = new Date(currentYear, currentMonth, 1).getDay();
            const daysInMonth = new Date(currentYear, currentMonth + 1, 0).getDate();

            let row = document.createElement("tr");

            // kosong awal
            for (let i = 0; i < firstDay; i++) {
                row.innerHTML += `<td></td>`;
            }

            for (let day = 1; day <= daysInMonth; day++) {
                const isActive =
                    day === selectedDate.getDate() &&
                    currentMonth === selectedDate.getMonth() &&
                    currentYear === selectedDate.getFullYear();

                const dateStr = formatDate(new Date(currentYear, currentMonth, day));
                const hasSchedule = schedules.some(s => s.date === dateStr);

                const buttonClass = isActive ? "btn-success text-white" : "btn-light";
                const underline = hasSchedule ? "border-bottom: 3px solid #10B981;" : "";

                row.innerHTML += `
                    <td class="text-center">
                        <button class="btn btn-sm rounded-circle ${buttonClass}"
                                style="${underline}"
                                onclick="selectDate(${day})">
                            ${day}
                        </button>
                    </td>
                `;

                if ((firstDay + day) % 7 === 0) {
                    tbody.appendChild(row);
                    row = document.createElement("tr");
                }
            }

            if (row.children.length > 0) {
                tbody.appendChild(row);
            }
        }

        /* =========================
        DATE SELECT
        ========================= */
        function selectDate(day) {
            selectedDate = new Date(currentYear, currentMonth, day);

            document.getElementById("current-date").textContent =
                `${dayNames[selectedDate.getDay()]}, ${day} ${monthNames[currentMonth]} ${currentYear}`;

            renderCalendar();
            renderSchedules();
        }

        /* =========================
        SCHEDULE LIST
        ========================= */
        function renderSchedules() {
            const container = document.getElementById("schedule-content");
            container.innerHTML = "";

            const today = formatDate(selectedDate);
            const todaySchedules = schedules.filter(s => s.date === today);

            if (todaySchedules.length === 0) {
                container.innerHTML = `<p class="text-muted">Tidak ada jadwal.</p>`;
                return;
            }

            todaySchedules.forEach(item => {
                let badgeClass = 'primary';
                if (item.type === 'maintenance') badgeClass = 'danger';
                if (item.type === 'task') badgeClass = 'info';

                container.innerHTML += `
                    <div class="mb-3 p-3 rounded-3 bg-light shadow-sm border-start border-4 border-${badgeClass}">
                        <div class="d-flex justify-content-between align-items-center mb-1">
                                <strong>${item.title}</strong>
                                <span class="badge bg-${badgeClass}">${item.type.toUpperCase()}</span>
                            </div>
                        <div class="text-muted small mb-1"><i class="fas fa-clock me-1"></i> ${item.time}</div>
                        <div class="text-muted small">${item.description}</div>
                        ${item.status ? `<div class="mt-2 text-end"><span class="badge bg-secondary">${item.status}</span></div>` : ''}
                    </div>
                `;
            });
        }

        /* =========================
        STATS GENERATION
        ========================= */
        function generateStats() {
            const today = formatDate(new Date());
            const todaySchedules = schedules.filter(s => s.date === today);

            // Stats logic can be expanded
            const maintenanceCount = schedules.filter(s => s.type === 'maintenance').length;
            const taskCount = schedules.filter(s => s.type === 'task').length;

            document.getElementById('stats-container').innerHTML = `
                <div class="col-md-4">
                    <div class="card border-0 shadow-sm rounded-4 h-100">
                        <div class="card-body p-4 text-center">
                            <div class="bg-primary bg-opacity-10 rounded-circle d-inline-flex align-items-center justify-content-center mb-3" style="width: 60px; height: 60px;">
                                <i class="fas fa-calendar-check fs-3 text-primary"></i>
                            </div>
                            <h3 class="fw-bold text-primary mb-1">${todaySchedules.length}</h3>
                            <p class="text-muted mb-0">Jadwal Hari Ini</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card border-0 shadow-sm rounded-4 h-100">
                        <div class="card-body p-4 text-center">
                            <div class="bg-warning bg-opacity-10 rounded-circle d-inline-flex align-items-center justify-content-center mb-3" style="width: 60px; height: 60px;">
                                <i class="fas fa-tools fs-3 text-warning"></i>
                            </div>
                            <h3 class="fw-bold text-warning mb-1">${maintenanceCount}</h3>
                            <p class="text-muted mb-0">Total Maintenance</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card border-0 shadow-sm rounded-4 h-100">
                        <div class="card-body p-4 text-center">
                            <div class="bg-info bg-opacity-10 rounded-circle d-inline-flex align-items-center justify-content-center mb-3" style="width: 60px; height: 60px;">
                                <i class="fas fa-tasks fs-3 text-info"></i>
                            </div>
                            <h3 class="fw-bold text-info mb-1">${taskCount}</h3>
                            <p class="text-muted mb-0">Total Tasks</p>
                        </div>
                    </div>
                </div>
            `;
        }

        /* =========================
        INIT
        ========================= */
        document.addEventListener("DOMContentLoaded", () => {
            generateStats();
            selectDate(selectedDate.getDate());
        });
    </script>
@endsection